/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing Accessors
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccessorsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Accessors
        //private Accessors instance;

        public AccessorsTests()
        {
            // TODO uncomment below to create an instance of Accessors
            //instance = new Accessors();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Accessors
        /// </summary>
        [Fact]
        public void AccessorsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Accessors
            //Assert.IsType<Accessors>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Iterable'
        /// </summary>
        [Fact]
        public void IterableTest()
        {
            // TODO unit test for the property 'Iterable'
        }
    }
}
