/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing Allocations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AllocationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Allocations
        //private Allocations instance;

        public AllocationsTests()
        {
            // TODO uncomment below to create an instance of Allocations
            //instance = new Allocations();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Allocations
        /// </summary>
        [Fact]
        public void AllocationsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Allocations
            //Assert.IsType<Allocations>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Iterable'
        /// </summary>
        [Fact]
        public void IterableTest()
        {
            // TODO unit test for the property 'Iterable'
        }
    }
}
