/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing AssetReclassification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetReclassificationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetReclassification
        //private AssetReclassification instance;

        public AssetReclassificationTests()
        {
            // TODO uncomment below to create an instance of AssetReclassification
            //instance = new AssetReclassification();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetReclassification
        /// </summary>
        [Fact]
        public void AssetReclassificationInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetReclassification
            //Assert.IsType<AssetReclassification>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Ext'
        /// </summary>
        [Fact]
        public void ExtTest()
        {
            // TODO unit test for the property 'Ext'
        }

        /// <summary>
        /// Test the property 'Asset'
        /// </summary>
        [Fact]
        public void AssetTest()
        {
            // TODO unit test for the property 'Asset'
        }
    }
}
