/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing AssetFilterTimestamp
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetFilterTimestampTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetFilterTimestamp
        //private AssetFilterTimestamp instance;

        public AssetFilterTimestampTests()
        {
            // TODO uncomment below to create an instance of AssetFilterTimestamp
            //instance = new AssetFilterTimestamp();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetFilterTimestamp
        /// </summary>
        [Fact]
        public void AssetFilterTimestampInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetFilterTimestamp
            //Assert.IsType<AssetFilterTimestamp>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'Between'
        /// </summary>
        [Fact]
        public void BetweenTest()
        {
            // TODO unit test for the property 'Between'
        }
    }
}
