/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing ClassificationGenericEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClassificationGenericEnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClassificationGenericEnum
        //private ClassificationGenericEnum instance;

        public ClassificationGenericEnumTests()
        {
            // TODO uncomment below to create an instance of ClassificationGenericEnum
            //instance = new ClassificationGenericEnum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClassificationGenericEnum
        /// </summary>
        [Fact]
        public void ClassificationGenericEnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClassificationGenericEnum
            //Assert.IsType<ClassificationGenericEnum>(instance);
        }
    }
}
