/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing ConversationGrounding
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConversationGroundingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConversationGrounding
        //private ConversationGrounding instance;

        public ConversationGroundingTests()
        {
            // TODO uncomment below to create an instance of ConversationGrounding
            //instance = new ConversationGrounding();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConversationGrounding
        /// </summary>
        [Fact]
        public void ConversationGroundingInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConversationGrounding
            //Assert.IsType<ConversationGrounding>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

        /// <summary>
        /// Test the property 'Temporal'
        /// </summary>
        [Fact]
        public void TemporalTest()
        {
            // TODO unit test for the property 'Temporal'
        }
    }
}
