/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing InteractedAssetInteractions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InteractedAssetInteractionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InteractedAssetInteractions
        //private InteractedAssetInteractions instance;

        public InteractedAssetInteractionsTests()
        {
            // TODO uncomment below to create an instance of InteractedAssetInteractions
            //instance = new InteractedAssetInteractions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InteractedAssetInteractions
        /// </summary>
        [Fact]
        public void InteractedAssetInteractionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" InteractedAssetInteractions
            //Assert.IsType<InteractedAssetInteractions>(instance);
        }

        /// <summary>
        /// Test the property 'Viewed'
        /// </summary>
        [Fact]
        public void ViewedTest()
        {
            // TODO unit test for the property 'Viewed'
        }

        /// <summary>
        /// Test the property 'Touched'
        /// </summary>
        [Fact]
        public void TouchedTest()
        {
            // TODO unit test for the property 'Touched'
        }

        /// <summary>
        /// Test the property 'Scrolled'
        /// </summary>
        [Fact]
        public void ScrolledTest()
        {
            // TODO unit test for the property 'Scrolled'
        }
    }
}
