/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing QGPTRelevanceInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QGPTRelevanceInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QGPTRelevanceInput
        //private QGPTRelevanceInput instance;

        public QGPTRelevanceInputTests()
        {
            // TODO uncomment below to create an instance of QGPTRelevanceInput
            //instance = new QGPTRelevanceInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QGPTRelevanceInput
        /// </summary>
        [Fact]
        public void QGPTRelevanceInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" QGPTRelevanceInput
            //Assert.IsType<QGPTRelevanceInput>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'Paths'
        /// </summary>
        [Fact]
        public void PathsTest()
        {
            // TODO unit test for the property 'Paths'
        }

        /// <summary>
        /// Test the property 'Seeds'
        /// </summary>
        [Fact]
        public void SeedsTest()
        {
            // TODO unit test for the property 'Seeds'
        }

        /// <summary>
        /// Test the property 'Assets'
        /// </summary>
        [Fact]
        public void AssetsTest()
        {
            // TODO unit test for the property 'Assets'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }

        /// <summary>
        /// Test the property 'Application'
        /// </summary>
        [Fact]
        public void ApplicationTest()
        {
            // TODO unit test for the property 'Application'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'Temporal'
        /// </summary>
        [Fact]
        public void TemporalTest()
        {
            // TODO unit test for the property 'Temporal'
        }
    }
}
