/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing QGPTPromptPipeline
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QGPTPromptPipelineTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QGPTPromptPipeline
        //private QGPTPromptPipeline instance;

        public QGPTPromptPipelineTests()
        {
            // TODO uncomment below to create an instance of QGPTPromptPipeline
            //instance = new QGPTPromptPipeline();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QGPTPromptPipeline
        /// </summary>
        [Fact]
        public void QGPTPromptPipelineInstanceTest()
        {
            // TODO uncomment below to test "IsType" QGPTPromptPipeline
            //Assert.IsType<QGPTPromptPipeline>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Task'
        /// </summary>
        [Fact]
        public void TaskTest()
        {
            // TODO unit test for the property 'Task'
        }

        /// <summary>
        /// Test the property 'Conversation'
        /// </summary>
        [Fact]
        public void ConversationTest()
        {
            // TODO unit test for the property 'Conversation'
        }
    }
}
