/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing SeededFile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SeededFileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SeededFile
        //private SeededFile instance;

        public SeededFileTests()
        {
            // TODO uncomment below to create an instance of SeededFile
            //instance = new SeededFile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeededFile
        /// </summary>
        [Fact]
        public void SeededFileInstanceTest()
        {
            // TODO uncomment below to test "IsType" SeededFile
            //Assert.IsType<SeededFile>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Bytes'
        /// </summary>
        [Fact]
        public void BytesTest()
        {
            // TODO unit test for the property 'Bytes'
        }

        /// <summary>
        /// Test the property 'VarString'
        /// </summary>
        [Fact]
        public void VarStringTest()
        {
            // TODO unit test for the property 'VarString'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
