/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing SensitiveMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SensitiveMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SensitiveMetadata
        //private SensitiveMetadata instance;

        public SensitiveMetadataTests()
        {
            // TODO uncomment below to create an instance of SensitiveMetadata
            //instance = new SensitiveMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SensitiveMetadata
        /// </summary>
        [Fact]
        public void SensitiveMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" SensitiveMetadata
            //Assert.IsType<SensitiveMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Match'
        /// </summary>
        [Fact]
        public void MatchTest()
        {
            // TODO unit test for the property 'Match'
        }

        /// <summary>
        /// Test the property 'Entropy'
        /// </summary>
        [Fact]
        public void EntropyTest()
        {
            // TODO unit test for the property 'Entropy'
        }
    }
}
