/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing TrackedAssetsEventSearchMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackedAssetsEventSearchMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrackedAssetsEventSearchMetadata
        //private TrackedAssetsEventSearchMetadata instance;

        public TrackedAssetsEventSearchMetadataTests()
        {
            // TODO uncomment below to create an instance of TrackedAssetsEventSearchMetadata
            //instance = new TrackedAssetsEventSearchMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrackedAssetsEventSearchMetadata
        /// </summary>
        [Fact]
        public void TrackedAssetsEventSearchMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrackedAssetsEventSearchMetadata
            //Assert.IsType<TrackedAssetsEventSearchMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
    }
}
