/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing TrackedAssetsEventSearchMetadataResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackedAssetsEventSearchMetadataResultsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrackedAssetsEventSearchMetadataResults
        //private TrackedAssetsEventSearchMetadataResults instance;

        public TrackedAssetsEventSearchMetadataResultsTests()
        {
            // TODO uncomment below to create an instance of TrackedAssetsEventSearchMetadataResults
            //instance = new TrackedAssetsEventSearchMetadataResults();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrackedAssetsEventSearchMetadataResults
        /// </summary>
        [Fact]
        public void TrackedAssetsEventSearchMetadataResultsInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrackedAssetsEventSearchMetadataResults
            //Assert.IsType<TrackedAssetsEventSearchMetadataResults>(instance);
        }

        /// <summary>
        /// Test the property 'Fuzzy'
        /// </summary>
        [Fact]
        public void FuzzyTest()
        {
            // TODO unit test for the property 'Fuzzy'
        }

        /// <summary>
        /// Test the property 'Exact'
        /// </summary>
        [Fact]
        public void ExactTest()
        {
            // TODO unit test for the property 'Exact'
        }

        /// <summary>
        /// Test the property 'Assets'
        /// </summary>
        [Fact]
        public void AssetsTest()
        {
            // TODO unit test for the property 'Assets'
        }

        /// <summary>
        /// Test the property 'Space'
        /// </summary>
        [Fact]
        public void SpaceTest()
        {
            // TODO unit test for the property 'Space'
        }
    }
}
