/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pieces.Os.Core.SdkModel;
using Pieces.Os.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pieces.Os.Core.Test.Model
{
    /// <summary>
    ///  Class for testing TrackedFormatEventIdentifierDescriptionPairs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackedFormatEventIdentifierDescriptionPairsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrackedFormatEventIdentifierDescriptionPairs
        //private TrackedFormatEventIdentifierDescriptionPairs instance;

        public TrackedFormatEventIdentifierDescriptionPairsTests()
        {
            // TODO uncomment below to create an instance of TrackedFormatEventIdentifierDescriptionPairs
            //instance = new TrackedFormatEventIdentifierDescriptionPairs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrackedFormatEventIdentifierDescriptionPairs
        /// </summary>
        [Fact]
        public void TrackedFormatEventIdentifierDescriptionPairsInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrackedFormatEventIdentifierDescriptionPairs
            //Assert.IsType<TrackedFormatEventIdentifierDescriptionPairs>(instance);
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'FormatCreated'
        /// </summary>
        [Fact]
        public void FormatCreatedTest()
        {
            // TODO unit test for the property 'FormatCreated'
        }

        /// <summary>
        /// Test the property 'FormatCopied'
        /// </summary>
        [Fact]
        public void FormatCopiedTest()
        {
            // TODO unit test for the property 'FormatCopied'
        }

        /// <summary>
        /// Test the property 'FormatPartiallyCopied'
        /// </summary>
        [Fact]
        public void FormatPartiallyCopiedTest()
        {
            // TODO unit test for the property 'FormatPartiallyCopied'
        }

        /// <summary>
        /// Test the property 'FormatDownloaded'
        /// </summary>
        [Fact]
        public void FormatDownloadedTest()
        {
            // TODO unit test for the property 'FormatDownloaded'
        }

        /// <summary>
        /// Test the property 'FormatDeleted'
        /// </summary>
        [Fact]
        public void FormatDeletedTest()
        {
            // TODO unit test for the property 'FormatDeleted'
        }

        /// <summary>
        /// Test the property 'FormatGenericClassificationUpdated'
        /// </summary>
        [Fact]
        public void FormatGenericClassificationUpdatedTest()
        {
            // TODO unit test for the property 'FormatGenericClassificationUpdated'
        }

        /// <summary>
        /// Test the property 'FormatSpecificClassificationUpdated'
        /// </summary>
        [Fact]
        public void FormatSpecificClassificationUpdatedTest()
        {
            // TODO unit test for the property 'FormatSpecificClassificationUpdated'
        }

        /// <summary>
        /// Test the property 'FormatUpdated'
        /// </summary>
        [Fact]
        public void FormatUpdatedTest()
        {
            // TODO unit test for the property 'FormatUpdated'
        }

        /// <summary>
        /// Test the property 'FormatInserted'
        /// </summary>
        [Fact]
        public void FormatInsertedTest()
        {
            // TODO unit test for the property 'FormatInserted'
        }

        /// <summary>
        /// Test the property 'FormatValueEdited'
        /// </summary>
        [Fact]
        public void FormatValueEditedTest()
        {
            // TODO unit test for the property 'FormatValueEdited'
        }
    }
}
