/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Pieces.Os.Core.Client.OpenAPIDateConverter;

namespace Pieces.Os.Core.SdkModel
{
    /// <summary>
    /// This is an enum that will help provide information around what permission this person has in relate to their scope.
    /// </summary>
    /// <value>This is an enum that will help provide information around what permission this person has in relate to their scope.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PersonAccessScopedEnum
    {
        /// <summary>
        /// Enum OWNER for value: OWNER
        /// </summary>
        [EnumMember(Value = "OWNER")]
        OWNER = 1,

        /// <summary>
        /// Enum EDITOR for value: EDITOR
        /// </summary>
        [EnumMember(Value = "EDITOR")]
        EDITOR = 2,

        /// <summary>
        /// Enum COMMENTER for value: COMMENTER
        /// </summary>
        [EnumMember(Value = "COMMENTER")]
        COMMENTER = 3,

        /// <summary>
        /// Enum VIEWER for value: VIEWER
        /// </summary>
        [EnumMember(Value = "VIEWER")]
        VIEWER = 4
    }

}
