/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Pieces.Os.Core.Client.OpenAPIDateConverter;

namespace Pieces.Os.Core.SdkModel
{
    /// <summary>
    /// Contains array of TLPDirectedDiscoveryFilter
    /// </summary>
    [DataContract(Name = "TLPDirectedDiscoveryFilters")]
    public partial class TLPDirectedDiscoveryFilters : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TLPDirectedDiscoveryFilters" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TLPDirectedDiscoveryFilters() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TLPDirectedDiscoveryFilters" /> class.
        /// </summary>
        /// <param name="iterable">Array that contains filters like class/function/loop (required).</param>
        public TLPDirectedDiscoveryFilters(List<TLPDirectedDiscoveryFilter> iterable = default(List<TLPDirectedDiscoveryFilter>))
        {
            // to ensure "iterable" is required (not null)
            if (iterable == null)
            {
                throw new ArgumentNullException("iterable is a required property for TLPDirectedDiscoveryFilters and cannot be null");
            }
            this.Iterable = iterable;
        }

        /// <summary>
        /// Array that contains filters like class/function/loop
        /// </summary>
        /// <value>Array that contains filters like class/function/loop</value>
        [DataMember(Name = "iterable", IsRequired = true, EmitDefaultValue = true)]
        public List<TLPDirectedDiscoveryFilter> Iterable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TLPDirectedDiscoveryFilters {\n");
            sb.Append("  Iterable: ").Append(Iterable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

            /// <summary>
            /// To validate all properties of the instance
            /// </summary>
            /// <param name="validationContext">Validation context</param>
            /// <returns>Validation Result</returns>
            IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
            {
            yield break;
        }
    }

}
