/*
 * Pieces Isomorphic OpenAPI
 *
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Pieces.Os.Core.Client;
using Pieces.Os.Core.Api;
// uncomment below to import models
//using Pieces.Os.Core.SdkModel;

namespace Pieces.Os.Core.Test.Api
{
    /// <summary>
    ///  Class for testing DistributionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DistributionsApiTests : IDisposable
    {
        private DistributionsApi instance;

        public DistributionsApiTests()
        {
            instance = new DistributionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DistributionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DistributionsApi
            //Assert.IsType<DistributionsApi>(instance);
        }

        /// <summary>
        /// Test DistributionsCreateNewDistribution
        /// </summary>
        [Fact]
        public void DistributionsCreateNewDistributionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SeededDistribution seededDistribution = null;
            //var response = instance.DistributionsCreateNewDistribution(seededDistribution);
            //Assert.IsType<Distribution>(response);
        }

        /// <summary>
        /// Test DistributionsDeleteSpecificDistribution
        /// </summary>
        [Fact]
        public void DistributionsDeleteSpecificDistributionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string distribution = null;
            //instance.DistributionsDeleteSpecificDistribution(distribution);
        }

        /// <summary>
        /// Test DistributionsSnapshot
        /// </summary>
        [Fact]
        public void DistributionsSnapshotTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.DistributionsSnapshot();
            //Assert.IsType<Distributions>(response);
        }
    }
}
